apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
    labels:
        argocd.argoproj.io/instance: {{ .cluster.name }}-external-secrets
    name: "{{ .cluster.name }}-{{ .cluster.stage }}"
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        key: ca.crt
        name: bitwarden-tls-certs
        namespace: external-secrets
        type: Secret
      identityURL: https://vault.bitwarden.com/identity
      organizationID: 3a74e159-50b1-4208-ad1d-b41600b913d7
      projectID: 70c9962e-a987-47b7-b86d-b41600b96b19

